name: COVID Box

on:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Saika-Z/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: 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
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: ${{ secrets.GIST_ID }}
