name: COVID Box

on:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: Saika-Z/covid-box@master
     # - name: Update gist
        #uses: Saika-Z/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          COUNTRY: ${{ secrets.COUNTRY }}
          GIST_ID: 51180172b81924cbb5d5b2d53ee9ec4d
